name: twod_representative
description: "A twod (2D) representative application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # firebase
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  firebase_performance: ^0.9.3+18
  recaptcha_enterprise_flutter: ^18.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  import_sorter: ^4.6.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/src\/[**/*.g.dart|**/*.gr.dart|**/*.freezed.dart]
