name: twod_representative
description: "A twod (2D) representative application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # firebase
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_crashlytics: ^3.4.19
  firebase_analytics: ^10.8.10
  firebase_performance: ^0.9.3+18
  recaptcha_enterprise_flutter: ^18.4.2

  # hooks and riverpod
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  equatable: ^2.0.5

  auto_route: ^7.9.0
  intl: ^0.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  import_sorter: ^4.6.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/src\/[**/*.g.dart|**/*.gr.dart|**/*.freezed.dart]
